datasource:
  runelite:
    jndiName: java:comp/env/jdbc/runelite
  runelite-cache:
    jndiName: java:comp/env/jdbc/runelite-cache2

# By default Spring tries to register the datasource as an MXBean,
# so if multiple apis are deployed on one web container with
# shared datasource it tries to register it multiples times and
# fails when starting the 2nd api
spring.jmx.enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

# Google OAuth client
oauth:
  client-id:
  client-secret:
  callback: https://api.runelite.net/oauth/
  callback-snapshot: https://api.runelite.net/oauth-snapshot/

# Redis client
redis:
  pool.size: 10
  host: tcp://localhost:6379

mongo:
  jndiName: java:comp/env/mongodb/runelite
  database: runelite

runelite:
  version: @project.version@
  commit: @git.commit.id.abbrev@
  dirty: @git.dirty@
  wiki:
    poll.ms: 300000 # 5 minutes
    url: https://prices.runescape.wiki/api/v1/osrs/latest
  price:
    cache: 30 # minutes
  worlds:
    url: http://www.runescape.com/g=oldscape/slr.ws?order=LPWM
  item:
    digestUrl: https://secure.runescape.com/m=itemdb_oldschool/digest.csv